In [6]:
import pandas as pd
pd.options.display.max_colwidth = None
pd.options.display.max_columns = None
df = pd.read_csv("/Users/rachelp/Documents/disabilities_number_and_wages_data.csv")
df.head()

,Unnamed: 0,Unnamed: 1,Total employed workers,Margin of error,Workers with a disability,Margin of error.1,Percent of workers in occupation with a disability,Margin of error.2,16-44 years,Margin of error.3,45-59 years,Margin of error.4,60 + years,Margin of error.5,With a disability median,Margin of error.6,No disability median,Margin of error.7,With a disability percent,Margin of error.8,No disability percent,Margin of error.9,With a disability median income,Margin of error.10,No disability median icnome,Margin of error.11
0,Total,Total,"155,041,900","138,778","9,085,980","51,790",5.9,0.03,"3,406,230","30,560","3,146,680","28,820","2,533,070","27,622",51.5,0.10,41.3,0.10,58.3,0.23,71.3,0.06,"41,332",167,"47,279",72
1,"Management, Business, Science, and Arts Occupations",Summary,"59,155,285","186,745","2,692,860","27,493",4.6,0.05,"865,520","15,988","954,490","14,336","872,845","15,180",53.4,0.20,43.2,0.10,68.8,0.45,77.9,0.08,"60,233",315,"66,310",94
2,"Management, Business, and Financial Occupations",Summary,"24,008,060","91,850","1,114,300","15,510",4.6,0.06,"312,665","9,115","417,505","7,910","384,130","9,259",54.6,0.30,45.2,0.10,76.4,0.63,86.1,0.10,"62,620","1,258","71,924",154
3,Management Occupations,Summary,"16,331,700","72,089","767,440","13,444",4.7,0.08,"205,560","7,278","295,035","7,232","266,840","8,338",55.0,0.30,46.0,0.10,78.3,0.77,87.7,0.11,"65,623","1,009","75,918",222
4,Chief executives,Detailed,"1,229,375","18,387","59,150","3,966",4.8,0.31,"8,255","1,605","18,035","2,308","32,860","2,985",62.0,1.20,52.1,0.20,77.2,2.38,89.9,0.42,"105,849","12,292","136,412","3,564"

In [10]:
df.sort_values(by='Percent of workers in occupation with a disability', ascending=False).head(10)

,Unnamed: 0,Unnamed: 1,Total employed workers,Margin of error,Workers with a disability,Margin of error.1,Percent of workers in occupation with a disability,Margin of error.2,16-44 years,Margin of error.3,45-59 years,Margin of error.4,60 + years,Margin of error.5,With a disability median,Margin of error.6,No disability median,Margin of error.7,With a disability percent,Margin of error.8,No disability percent,Margin of error.9,With a disability median income,Margin of error.10,No disability median icnome,Margin of error.11
19,"Farmers, ranchers, and other agricultural managers",Detailed,"537,210","10,445","49,815","2,818",9.3,0.52,"6,210","1,119","12,990","1,695","30,615","2,413",63.9,1.10,51.5,0.50,69.9,2.74,82.8,0.83,"39,139","4,353","42,159",594
234,Security guards and gaming surveillance officers,Detailed,"979,390","18,043","90,725","5,195",9.3,0.48,"31,075","3,120","24,930","2,954","34,720","2,769",55.0,1.80,38.3,0.50,57.6,2.87,69.4,0.86,"28,703","2,653","31,671",307
298,"Door-to-door sales workers, news and street vendors, and related workers",Detailed,"131,705","6,388","12,275","1,669",9.3,1.26,"4,350","1,136","4,105","1,173","3,820",927,52.4,3.50,42.8,1.30,24.0,7.21,36.4,2.25,"30,522","10,985","30,827","1,442"
539,Automotive and watercraft service attendants,Detailed,"92,400","5,149","8,560","1,500",9.3,1.55,"4,895","1,303","1,945",602,"1,720",629,37.3,5.70,29.3,1.60,43.2,10.27,60.9,3.32,"21,852","1,088","24,396","1,453"
526,Bus drivers,Detailed,"576,720","14,341","53,870","3,221",9.3,0.54,"8,345","1,840","17,390","2,210","28,135","1,838",60.8,1.30,53.6,0.40,37.5,3.49,49.6,1.43,"29,858","2,024","35,240",912
552,"Packers and packagers, hand",Detailed,"520,790","13,475","48,085","3,730",9.2,0.70,"24,810","3,147","16,480","2,392","6,790","1,160",44.0,2.80,37.8,0.70,40.4,4.09,64.3,1.37,"24,028","1,804","24,703",467
321,"Interviewers, except eligibility and loan",Detailed,"131,780","6,076","12,015","1,839",9.1,1.35,"3,295","1,024","5,505","1,422","3,215",732,52.4,3.10,42.1,1.70,55.2,8.04,65.7,2.41,"37,201","2,430","33,608","1,776"
252,Building and Grounds Cleaning and Maintenance Occupations,Summary,"6,009,605","43,650","549,320","12,741",9.1,0.20,"190,005","7,692","204,940","8,014","154,370","6,752",52.5,0.50,44.8,0.20,42.9,1.23,61.3,0.36,"26,789",497,"27,680",301
457,"Cutting, punching, and press machine setters, operators, and tenders, metal and plastic",Detailed,"84,175","5,015","7,620","1,385",9.1,1.56,"1,740",671,"4,570","1,210","1,305",427,50.5,5.20,41.8,1.90,71.0,9.31,82.4,2.67,"36,545","7,086","35,246","1,002"
347,"Mail clerks and mail machine operators, except postal service",Detailed,"77,510","3,954","6,925","1,170",8.9,1.51,"1,600",620,"2,920",780,"2,405",666,54.1,3.00,42.5,2.80,65.3,9.48,63.5,3.80,"30,194","2,779","31,855","1,092"